# Generated by Django 3.2.4 on 2021-06-25 01:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bidPrice',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='bidder',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='commentPoster',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='downVotes',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='upVotes',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='lister',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='price',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='bid',
            name='listingid',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='bid',
            name='title',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='bid',
            name='user',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='comments',
            name='listingid',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='comments',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 6, 25, 1, 27, 7, 466591, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 6, 25, 1, 27, 16, 19461, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='image_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='seller',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='listing',
            name='starting_bid',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
